### PR TITLE
Upgrade cdrkit

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by thwpike** [comment]
Hi @PeterDaveHello, thank you for the patch, can you make please also make sure it will apply cleanly against the v7client and arch_tuning branches?

**Comment by PeterDaveHello** [comment]
There are few small conflicts, I can send another patch to those 2 branches, it'll be okay.

**Comment by PeterDaveHello** [comment]
BTW, the files of v7 branch keep showing on my master branch, would you please merge #71? Previous PR not work at all.

**Comment by PeterDaveHello** [comment]
@thwpike Are we good to go?

**Comment by thwpike** [comment]
Hi @PeterDaveHello, most of this was actually done in e8a271fcdca017a29aba66f11cc07cb39a3f9546, I had been wondering whether to simply do the rest of the work to get the v7 client as the default as merging this now would make a bit of work later on to merge the v7client branch in.

**Comment by PeterDaveHello** [comment]
@thwpike, I believe that there will be some conflicts, on my opinion, I will use cherry-pick to pick them into master, not directly merge them, it may be easier to solve the conflicts, maybe I can do it if you don't mind, I think it's okay for me :smile:

**Comment by thwpike** [comment]
@PeterDaveHello, I bit the bullet and did a massive cherry-pick and merge in 1ec0211be4fe0be0b100f5d784f164aca3139a77 - it wasn't possible to directly merge this PR, but cdrkit is now at 1.1.11.  Hopefully this will make going to the v7 client easier.

**Pull request closed without merging**
